apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-website
bases:
- ../workload
images:
- name: devlaunchers/platform-website
  newName: devlaunchers/platform-website
  newTag: 8014220-202107292016 # {"$imagepolicy": "platform-website:platform-website:tag"}
patchesStrategicMerge:
- resource-patch.yaml
